# TCL File Generated by Component Editor 18.1
# Mon May 03 13:59:54 CDT 2021
# DO NOT MODIFY


# 
# blinky_test "blinky_test" v1.1
# Ben Klemp 2021.05.03.13:59:54
# Avalon test component
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module blinky_test
# 
set_module_property DESCRIPTION "Avalon test component"
set_module_property NAME blinky_test
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Custom
set_module_property AUTHOR "Ben Klemp"
set_module_property DISPLAY_NAME blinky_test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL blinky_test_port
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file blinky_test_port.vhd VHDL PATH ../components/lib/blinky_test_port.vhd TOP_LEVEL_FILE
add_fileset_file blinky_test.vhd VHDL PATH ../components/lib/blinky_test.vhd
add_fileset_file counter.vhd VHDL PATH ../components/lib/counter.vhd
add_fileset_file edge_detector.vhd VHDL PATH ../components/lib/edge_detector.vhd
add_fileset_file port_reg.vhd VHDL PATH ../components/lib/port_reg.vhd
add_fileset_file prescaler.vhd VHDL PATH ../components/lib/prescaler.vhd
add_fileset_file reg.vhd VHDL PATH ../components/lib/reg.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end oblinky export Output 1

